### ISSUE TITLE
helm push panic sigsegv 

### ISSUE THREAD

**Issue by bab5470** [chartmuseum/helm-push#108]
Getting this when trying to run a helm push. This WAS working so I'm uncertain why it suddenly stopped but now I can no longer push charts to my repo: 

helm push myhelmchart-0.1.0.tgz p2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12d77c9]

goroutine 1 [running]:
github.com/chartmuseum/helm-push/pkg/helm.LoadIndex(0xc000253a00, 0x0, 0x200, 0x0, 0x0, 0x40dfd8)
        /home/runner/work/helm-push/helm-push/pkg/helm/index.go:48 +0xc9
github.com/chartmuseum/helm-push/pkg/helm.GetIndexByDownloader(0xc000607ab8, 0xc0003bcac0, 0xc000607ac8, 0x130804d)
        /home/runner/work/helm-push/helm-push/pkg/helm/index.go:39 +0x58
github.com/chartmuseum/helm-push/pkg/helm.GetIndexByRepo(0xc0000bc398, 0xc0003bcac0, 0xa, 0xc0004062c0, 0x0)
        /home/runner/work/helm-push/helm-push/pkg/helm/index.go:26 +0x5c
main.(*pushCmd).push(0xc0000ea0f0, 0x0, 0x0)
        /home/runner/work/helm-push/helm-push/cmd/helmpush/main.go:302 +0x858
main.newPushCmd.func1(0xc0002e6b00, 0xc00000c7a0, 0x2, 0x2, 0x0, 0x0)
        /home/runner/work/helm-push/helm-push/cmd/helmpush/main.go:108 +0x113
github.com/spf13/cobra.(*Command).execute(0xc0002e6b00, 0xc000098160, 0x2, 0x2, 0xc0002e6b00, 0xc000098160)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.0/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002e6b00, 0x2, 0x2, 0xc0002e6b00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.0/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.0/command.go:895
main.main()
        /home/runner/work/helm-push/helm-push/cmd/helmpush/main.go:438 +0x76
Error: plugin "push" exited with error

Is there some way to tell why helm push is crashing?

Thanks
Brad

**Comment by bab5470** [comment]
# helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

**Comment by kaflake** [comment]
I have the same error. You find a solution?
